/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.chai.memms.reports.dashboard

/**
 *
 * @author donatien,ANTOINE,PIVOT ACCESS LTD
 */
class IndicatorDescriptor {
    //indicator category codes
    public static final String CORRECTIVE_MAINTENANCE="corrective"
    public static final String PRIVENTIVE_MAINTENANCE="preventive"
    public static final String MANAGEMENT_SPARE_PARTS="spare_parts"
    public static final String MANAGEMENT_EQUIPMENT="equipment"
    public static final String MONITORING_MEMMS_USE="monitoring"
 
    // inducator scripts 
    
    //Slid 7:Share of operational equipment
    public static final String SHARE_OPERATIONAL_SIMPLE_SLD7="select 1.0*count(equ.id)/(select count(equIn.id) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='OPERATIONAL' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_OPERATIONAL_GROUP_SLD7="select equ.type.names_en,1.0*count(equ.id)/(select count(equIn.id) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='OPERATIONAL' and equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 8:Share of equipment for disposal
    public static final String SHARE_DISPOSAL_SIMPLE_SLD8="select 1.0*count(equ.id)/(select count(equIn.id) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='FORDISPOSAL' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_DISPOSAL_GROUP_SLD8="select equ.type.names_en,1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='FORDISPOSAL' and equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 9:Share of equipment in stock
    public static final String SHARE_STOCK_SIMPLE_SLD9="select 1.0*count(equ.id)/(select count(equIn.id) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='INSTOCK' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_STOCK_GROUP_SLD9="select equ.type.names_en,1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus='INSTOCK' and equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 10:Degree of equipment standardization
    public static final String DEGREE_STANDARDIZATION_SIMPLE_SLD10="select sum(tmp2.max_eq)/tmp3.counter as final_result from (select max(tmp1.counter) as max_eq from (select type_id, manufacturer_id, count(id) as counter FROM memms_equipment where type_id is not null and manufacturer_id is not null and data_location_id @DATA_LOCATION group by type_id, manufacturer_id) tmp1 group by tmp1.type_id) tmp2, (select count(id) as counter from memms_equipment where current_status not in ('FORDISPOSAL','DISPOSED') and data_location_id @DATA_LOCATION) tmp3"
    public static final String DEGREE_STANDARDIZATION_GROUP_SLD10="select tmp4.names,tmp2.max_eq/tmp3.counter as final_result from (select max(tmp1.counter) as max_eq from (select ee.type_id, ee.manufacturer_id, count(ee.id) as counter FROM memms_equipment ee where ee.type_id is not null and ee.manufacturer_id is not null and ee.data_location_id @DATA_LOCATION group by ee.type_id, ee.manufacturer_id) tmp1 group by tmp1.type_id) tmp2,(select count(e.id) as counter from memms_equipment e,memms_equipment_type et where e.type_id=et.id and current_status not in ('FORDISPOSAL','DISPOSED') and data_location_id @DATA_LOCATION) tmp3,(select et.names_en as names from memms_equipment e,memms_equipment_type et where e.type_id=et.id and current_status not in ('FORDISPOSAL','DISPOSED') and data_location_id @DATA_LOCATION group by type_id) tmp4"
   
    //Slie 11:Share of equipment donated
    public static final String SHARE_DONATED_SIMPLE_SLD11="select 1.0*count(equ.id)/(select count(equIn.id) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equ.purchaser='BYDONOR' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_DONATED_GROUP_SLD11="select equ.type.names_en,1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equ.purchaser='BYDONOR' and equ.dataLocation @DATA_LOCATION group by equ.type"
     //Slie 12:Share of obsolete equipment
    public static final String SHARE_OBSOLETE_SIMPLE_SLD12="select 1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equ.obsolete=1 and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_OBSOLETE_GROUP_SLD12="select equ.type.names_en,1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equ.obsolete=1 and equ.dataLocation @DATA_LOCATION group by equ.type"
     //Slie 13:Share of equipment under active warranty or an active service provider contract
    public static final String SHARE_ACTIVE_WARANTY_SIMPLE_SLD13="select count(equ.code)/(select count(f.code) from memms_equipment f where f.current_status in ('OPERATIONAL','PARTIALLYOPERATIONAL','UNDERMAINTENANCE','INSTOCK') and f.data_location_id @DATA_LOCATION) as final_result from memms_equipment as equ where equ.current_status in ('OPERATIONAL','UNDERMAINTENANCE','PARTIALLYOPERATIONAL','INSTOCK') and (dateDiff(NOW(),equ.warranty_start_date)<(equ.warranty_period_number_of_months)*30 or dateDiff(NOW(),equ.service_contract_start_date)<(equ.service_contract_period_number_of_months)*30) and equ.data_location_id @DATA_LOCATION"
    public static final String SHARE_ACTIVE_WARANTY_GROUP_SLD13="select et.names_en,count(equ.code)/(select count(f.code) from memms_equipment f where f.current_status in ('OPERATIONAL','PARTIALLYOPERATIONAL','UNDERMAINTENANCE','INSTOCK') and f.data_location_id @DATA_LOCATION) as final_result from memms_equipment as equ,memms_equipment_type et where equ.type_id=et.id and equ.current_status in ('OPERATIONAL','UNDERMAINTENANCE','PARTIALLYOPERATIONAL','INSTOCK') and (dateDiff(NOW(),equ.warranty_start_date)<(equ.warranty_period_number_of_months)*30 or dateDiff(NOW(),equ.service_contract_start_date)<(equ.service_contract_period_number_of_months)*30) and equ.data_location_id @DATA_LOCATION group by equ.type_id"
    //Slie 14:Share of equipment with lifetime expiring in less than 2 years
    public static final String SHARE_LIFETIME_LESS_SIMPLE_SLD14="select 1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and ((dateDiff(NOW(),equ.purchaseDate)/12)>(equ.expectedLifeTime-24)) and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_LIFETIME_LESS_GROUP_SLD14="select equ.type.names_en, 1.0*count(equ.code)/(select count(equIn.code) as count1 from Equipment as equIn where equIn.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and equIn.dataLocation @DATA_LOCATION) from Equipment as equ where equ.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and ((dateDiff(NOW(),equ.purchaseDate)/12)>(equ.expectedLifeTime-24)) and equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 15:Share of equipments for which a work order was generated
    public static final String SHARE_WORK_ORDER_GEN_SIMPLE_SLD15="select 1.0*count(equ.code)/(select count(f.code) from Equipment f where f.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and f.dataLocation @DATA_LOCATION)  from WorkOrder wo join wo.equipment equ where wo.equipment.id is not null and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_WORK_ORDER_GEN_GROUP_SLD15="select equ.type.names_en,1.0*count(equ.code)/(select count(f.code) from Equipment f where f.currentStatus in ('OPERATIONAL','PARTIALLYOPERATIONAL', 'UNDERMAINTENANCE') and f.dataLocation @DATA_LOCATION)  from Equipment equ where equ.id in(select wo.equipment.id from WorkOrder wo) and equ.dataLocation @DATA_LOCATION group by  equ.type"
    //Slie 16:Degree of corrective maintenance execution according to benchmark
    public static final String DEGREE_CORRECTIVE_EX_SIMPLE_SLD16="select 1.0*count(wo1.id)/(select count(wo.id) from WorkOrderStatus wos join wos.workOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) from WorkOrderStatus wos1 join wos1.workOrder wo1 join wo1.equipment as equ1 where wo1.currentStatus='CLOSEDFIXED' and (dateDiff(NOW(),wo1.returnedOn) < #DEGGREE_CORRE_MAINT_EXECUTION or dateDiff(NOW(),wos1.dateCreated) < #DEGGREE_CORRE_MAINT_EXECUTION) and equ1.dataLocation @DATA_LOCATION"
    public static final String DEGREE_CORRECTIVE_EX_GROUP_SLD16="select equ1.type.names_en as names,1.0*count(wo1.id)/(select count(wo.id) from WorkOrderStatus wos join wos.workOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) as final_result from WorkOrderStatus wos1 join wos1.workOrder wo1 join wo1.equipment as equ1 where wo1.currentStatus='CLOSEDFIXED' and (dateDiff(NOW(),wo1.returnedOn) < #DEGGREE_CORRE_MAINT_EXECUTION or dateDiff(NOW(),wos1.dateCreated) < #DEGGREE_CORRE_MAINT_EXECUTION) and equ1.dataLocation @DATA_LOCATION group by equ1.type"
    //Slie 17:Share of work orders witnessing re-incidence in a period of time (user defined)
    public static final String SHARE_WORK_ORDER_WITNESSING_SIMPLE_SLD17="select count(temp1.reincidenceorders)/(select count(woo1.equipment_id) from memms_equipment equ1 left join memms_work_order woo1 on equ1.id=woo1.equipment_id where dateDiff(NOW(), woo1.open_on) <= #WO_REINCIDENCE_DAYS and equ1.data_location_id @DATA_LOCATION) as final_result from (select count(woo.equipment_id) as reincidenceorders from memms_equipment equ left join memms_work_order woo on equ.id=woo.equipment_id where dateDiff(NOW(), woo.open_on) <= #WO_REINCIDENCE_DAYS and equ.data_location_id @DATA_LOCATION group by woo.equipment_id) temp1 where temp1.reincidenceorders>=2"
    public static final String SHARE_WORK_ORDER_WITNESSING_GROUP_SLD17="select temp1.providername,count(temp1.reincidenceorders)/(select count(woo1.equipment_id) from memms_equipment equ1,memms_work_order woo1  where equ1.id=woo1.equipment_id and dateDiff(NOW(),woo1.open_on)<=#WO_REINCIDENCE_DAYS and equ1.data_location_id @DATA_LOCATION) as final_result from (select count(woo.equipment_id) as reincidenceorders,st.contact_contact_name as providername,st.id as providerid from memms_equipment equ,memms_provider st,memms_work_order woo  where equ.service_provider_id=st.id and equ.id=woo.equipment_id and dateDiff(NOW(),woo.open_on)<=#WO_REINCIDENCE_DAYS and equ.data_location_id @DATA_LOCATION group by equ.service_provider_id) temp1 where temp1.reincidenceorders>=2 group by temp1.providerid"
    
   //Slie 18:Cost effectiveness of corrective maintenance
    public static final String COST_EFF_CORR_SIMPLE_SLD18="select avg(temp_query.totalOrders) as final_result from (select sum(woo.estimated_cost)/equ.purchase_cost as totalOrders from memms_equipment equ,memms_work_order woo  where equ.id=woo.equipment_id and equ.data_location_id @DATA_LOCATION  group by woo.equipment_id) temp_query"
    public static final String COST_EFF_CORR_GROUP_SLD18="select temp_query.typename,avg(temp_query.totalOrders) as final_result from (select sum(woo.estimated_cost)/equ.purchase_cost as totalOrders,st.id as typeId,st.names_en as typename from memms_equipment equ,memms_equipment_type st,memms_work_order woo  where equ.type_id=st.id and equ.id=woo.equipment_id and equ.data_location_id @DATA_LOCATION  group by woo.equipment_id) temp_query where temp_query.totalOrders>0 group by temp_query.typeId"
     //Slie 19:Share of work orders escalated to MMC
    public static final String SHARE_ESCLATED_MMC_SIMPLE_SLD19="select 1.0*count(wo.id)/(select count(wo.id) from WorkOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) from WorkOrder wo join wo.equipment as equ where wo.currentStatus='OPENATMMC' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_ESCLATED_MMC_GROUP_SLD19="select equ.type.names_en,1.0*count(wo.id)/(select count(wo.id) from WorkOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) from WorkOrder wo join wo.equipment as equ where wo.currentStatus='OPENATMMC' and equ.dataLocation @DATA_LOCATION group by equ.type"
     //Slie 20:Average time to fix equipments
    public static final String AVGE_FIX_SIMPLE_SLD20="select avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed from memms_work_order wo ,memms_equipment equ,memms_work_order_status wos  where wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wos.status='OPENATFOSA' and equ.data_location_id @DATA_LOCATION) temp"
    public static final String AVGE_FIX_GROUP_SLD20="select temp.typeName,avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed , ty.names_en as typeName,ty.id as typeId from memms_work_order wo ,memms_equipment equ,memms_equipment_type ty,memms_work_order_status wos  where equ.type_id=ty.id and wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wos.status='OPENATFOSA' and equ.data_location_id @DATA_LOCATION) temp   group by temp.typeId"
    //Slie 21:Average time to fix equipments by the District Hospital technician
    public static final String AVGE_TIME_FIX_DH_SIMPLE_SLD21="select avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed from memms_work_order wo ,memms_equipment equ,memms_work_order_status wos  where wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wo.id not in(select wo.id from memms_work_order wo ,memms_equipment equ,memms_work_order_status wos  where wo.equipment_id=equ.id and wo.id=wos.work_order_id and wos.status='OPENATMMC' and equ.data_location_id @DATA_LOCATION) and equ.data_location_id @DATA_LOCATION) temp"
    public static final String AVGE_TIME_FIX_DH_GROUP_SLD21="select temp.nameEn,avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed,ty.id as typeId,ty.names_en as nameEn from memms_work_order wo ,memms_equipment equ,memms_equipment_type ty,memms_work_order_status wos  where equ.type_id=ty.id and wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wo.id not in(select wo.id from memms_work_order wo ,memms_equipment equ,memms_work_order_status wos  where wo.equipment_id=equ.id and wo.id=wos.work_order_id and wos.status='OPENATMMC' and equ.data_location_id @DATA_LOCATION) and equ.data_location_id @DATA_LOCATION) temp group by temp.typeId"
    
    //Slie 22:Average time to fix equipments by MMC
    public static final String AVGE_TIME_FIX_MMC_SIMPLE_SLD22="select avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed from memms_work_order wo ,memms_equipment equ,memms_work_order_status wos  where wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wos.status='OPENATMMC' and equ.data_location_id @DATA_LOCATION) temp"
    public static final String AVGE_TIME_FIX_MMC_GROUP_SLD22="select temp.nameEn,avg(temp.fromOpenToClosed) as final_result from (select dateDiff(wo.open_on,wos.date_created) as fromOpenToClosed,ty.names_en as nameEn,ty.id as typeId from memms_work_order wo ,memms_equipment equ,memms_equipment_type ty,memms_work_order_status wos  where equ.type_id=ty.id and wo.equipment_id=equ.id and wo.id=wos.work_order_id and wo.current_status='CLOSEDFIXED' and wos.status='OPENATMMC' and equ.data_location_id @DATA_LOCATION) temp group by temp.typeId;"
    //Slie 23:Share of work orders requiring new spare parts
    public static final String SHARE_WORK_ORDER_REQ_SP_SIMPLE_SLD23=""
    public static final String SHARE_WORK_ORDER_REQ_SP_GROUP_SLD23=""
    //Slie 24:Share of problems caused by misuse
    public static final String SHARE_PROBLEM_MISUSE_SIMPLE_SLD24="select 1.0*count(wo.id)/(select count(wo.id) from WorkOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) from WorkOrder wo join wo.equipment as equ where wo.failureReason='MISUSE' and equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_PROBLEM_MISUSE_GROUP_SLD24="select equ.type.names_en,1.0*count(wo.id)/(select count(wo.id) from WorkOrder wo join wo.equipment as equ where equ.dataLocation @DATA_LOCATION) from WorkOrder wo join wo.equipment as equ where wo.failureReason='MISUSE' and equ.dataLocation @DATA_LOCATION group by equ.type"
   
    //Slie 26:Degree of execution of preventive maintenance
    public static final String DEGREE_EXCUTION_PREV_SIMPLE_SLD26="select 1.0*count(prwo.id)/(select count(prwo.id) FROM PreventiveOrder prwo join prwo.equipment as equ1  where equ1.dataLocation @DATA_LOCATION) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION"
    public static final String DEGREE_EXCUTION_PREV_GROUP_SLD26="select equ.type.names_en,1.0*count(prwo.id)/(select count(prwo.id) FROM PreventiveOrder prwo join prwo.equipment as equ1  where equ1.dataLocation @DATA_LOCATION) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 27:Share of maintenance executed at the facility
    public static final String SHARE_MAIN_EXC_SIMPLE_SLD27="select 1.0*count(prwo.id)/(select count(prwo.id) FROM PreventiveOrder prwo join prwo.equipment as equ1  where equ1.dataLocation @DATA_LOCATION) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION"
    public static final String SHARE_MAIN_EXC_GROUP_SLD27="select equ.type.names_en,1.0*count(prwo.id)/(select count(prwo.id) FROM PreventiveOrder prwo join prwo.equipment as equ1  where equ1.dataLocation @DATA_LOCATION) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 28:Deviation against scheduled date
    public static final String DEVIATION_AGAIST_SIMPLE_SLD28="select ABS(avg(dateDiff(pr.eventDate,pr.scheduledOn))) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION"
    public static final String DEVIATION_AGAIST_GROUP_SLD28="select equ.type.names_en, ABS(avg(dateDiff(pr.eventDate,pr.scheduledOn))) FROM Prevention pr join pr.order as prwo join prwo.equipment as equ where equ.dataLocation @DATA_LOCATION group by equ.type"
    //Slie 29:Number of types of spare parts about to be discontinued in a year
    public static final String NUMBER_TYPE_SPARE_DISC_SIMPLE_SLD29="select count(sp.id) FROM SparePart sp join sp.type as sptp where dateDiff(sptp.discontinuedDate,NOW())<=365 and sp.dataLocation @DATA_LOCATION"
    public static final String NUMBER_TYPE_SPARE_DISC_GROUP_SLD29="select sptp.names_en,count(sp.id) FROM SparePart sp join sp.type as sptp where dateDiff(sptp.discontinuedDate,NOW())<=365 and sp.dataLocation @DATA_LOCATION group by sptp.id"
    //Slie 30:Share of types of spare parts about to stock out in a given time period
    public static final String SHARE_TYPE_SP_PART_STOCK_OUT_SIMPLE_SLD30="select count(temp.spTypeTimount)/(SELECT count(mmm.id)  FROM memms_spare_part mmm where mmm.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.type_id)/(SELECT ROUND((count(m.id)/12),0)  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as spTypeTimount   FROM memms_spare_part mm where mm.data_location_id @DATA_LOCATION group by mm.type_id) temp where temp.spTypeTimount<#TRASHHOLD_MIN_STOCT_OUT"
    public static final String SHARE_TYPE_SP_PART_STOCK_OUT_GROUP_SLD30="select temp.descen,temp.spTypeTimount/(SELECT count(mmm.id)  FROM memms_spare_part mmm where mmm.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.type_id)/(SELECT ROUND(count(m.id)/12)  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as spTypeTimount,spt.names_en as descen   FROM memms_spare_part mm,memms_spare_part_type spt where mm.type_id=spt.id and mm.data_location_id @DATA_LOCATION group by mm.type_id) temp where temp.spTypeTimount<#TRASHHOLD_MIN_STOCT_OUT"
    //Slie 31:Number of types of spare parts with stock more than a given time period
    public static final String NUMBER_SP_PAT_STOCK_MORE_SIMPLE_SLD31="select count(temp.spTypeTimount)/(SELECT count(mmm.id)  FROM memms_spare_part mmm where mmm.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.type_id)/(SELECT ROUND((count(m.id)/12),0)  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as spTypeTimount   FROM memms_spare_part mm where mm.data_location_id @DATA_LOCATION group by mm.type_id) temp where temp.spTypeTimount>#TRASHHOLD_MAX_STOCT_OUT"
    public static final String NUMBER_SP_PAT_STOCK_MORE_GROUP_SLD31="select temp.namesEn,temp.spTypeTimount/(SELECT count(mmm.id)  FROM memms_spare_part mmm where mmm.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.type_id)/(SELECT count(m.id)/12  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as spTypeTimount,spt.names_en as namesEn FROM memms_spare_part mm,memms_spare_part_type spt where mm.type_id=spt.id and mm.data_location_id @DATA_LOCATION group by mm.type_id) temp where temp.spTypeTimount>#TRASHHOLD_MAX_STOCT_OUT"
    
    //Slie 32:Average stock time
    public static final String AVG_STOCK_TIME_SIMPLE_SLD32="select sum(temp.usageeach)/(SELECT count(m.id)  FROM memms_spare_part m where m.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.id)/(SELECT ROUND((count(m.id)/12),0)  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as usageeach FROM memms_spare_part mm where mm.data_location_id @DATA_LOCATION group by mm.type_id) temp"
    public static final String AVG_STOCK_TIME_GROUP_SLD32="select temp.namesEn,temp.usageeach/(SELECT count(m.id)  FROM memms_spare_part m where m.data_location_id @DATA_LOCATION) as final_result from (SELECT count(mm.id)/(SELECT count(m.id)/12  FROM memms_spare_part m where m.status='OPERATIONAL' and dateDiff(NOW(),m.delivery_date)<=365 and m.data_location_id @DATA_LOCATION group by mm.type_id) as usageeach,spt.names_en as namesEn FROM memms_spare_part mm,memms_spare_part_type spt where mm.type_id=spt.id and mm.data_location_id @DATA_LOCATION group by mm.type_id) temp"
    //Slie 33:Average time between request and arrival of spare parts
    public static final String AVG_REQUEST_ARVAL_SIMPLE_SLD33="select ABS(ROUND(avg(dateDiff(sp.dateCreated,spst.dateOfEvent)),0)) from SparePartStatus spst join spst.sparePart as sp where sp.status='INSTOCK' and spst.statusOfSparePart='PENDINGORDER' and sp.dataLocation @DATA_LOCATION"
    public static final String AVG_REQUEST_ARVAL_GROUP_SLD33="select sp.type.names_en, ABS(ROUND(avg(dateDiff(sp.dateCreated,spst.dateOfEvent)),0)) from SparePartStatus spst join spst.sparePart as sp where sp.status='INSTOCK' and spst.statusOfSparePart='PENDINGORDER' and sp.dataLocation @DATA_LOCATION group by sp.type.id"
    //Slie 34:Average number of equipments per facility
    public static final String AVG_NUM_EQU_FAC_SIMPLE_SLD34="select count(equIn.id) as count1 from Equipment as equIn where  equIn.dataLocation @DATA_LOCATION"
    public static final String AVG_NUM_EQU_FAC_GROUP_SLD34="select equIn.dataLocation.names_en, count(equIn.id) as count1 from Equipment as equIn where  equIn.dataLocation @DATA_LOCATION group by equIn.dataLocation.id"
    //Slie 35:Share of facilities with less than 10 inventory status changes in a year
    public static final String SHARE_FAC_INVTORY_LESS_SIMPLE_SLD35="select count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.data_location_id) as counts_total FROM memms_equipment equ,memms_equipment_status equst  where equ.id=equst.equipment_id and equ.data_location_id @DATA_LOCATION and dateDiff(NOW(),equst.date_of_event) <=365 group by equ.data_location_id) temp1 where temp1.counts_total<10;"
    public static final String SHARE_FAC_INVTORY_LESS_GROUP_SLD35="select temp1.nameType,count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.data_location_id) as counts_total,locTy.id as typeId,locTy.names_en as nameType FROM memms_equipment equ,chai_location_data_location locc,chai_location_data_location_type locTy,memms_equipment_status equst  where equ.data_location_id=locc.id and locc.type=locTy.id and equ.id=equst.equipment_id and equ.data_location_id @DATA_LOCATION and dateDiff(NOW(),equst.date_of_event) <=365 group by equ.data_location_id) temp1 where temp1.counts_total<10 group by temp1.typeId"
    //Slie 36:Share of facilities with less than 10 work orders in a year
    public static final String SHARE_FAC_WORK_ORDER_LESS_SIMPLE_SLD36="select count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.data_location_id) as counts_total FROM memms_equipment equ,memms_work_order wo  where equ.id=wo.equipment_id and  equ.data_location_id @DATA_LOCATION and dateDiff(NOW(),wo.open_on)<=365 group by equ.data_location_id) temp1 where temp1.counts_total<10"
    public static final String SHARE_FAC_WORK_ORDER_LESS_GROUP_SLD36="select temp1.typeName,count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.data_location_id) as counts_total,locTy.id as typeid,locTy.names_en as typeName FROM memms_equipment equ,chai_location_data_location locc,chai_location_data_location_type locTy,memms_work_order wo  where equ.data_location_id=locc.id and locc.type=locTy.id and equ.id=wo.equipment_id and  equ.data_location_id @DATA_LOCATION and dateDiff(NOW(),wo.open_on)<=365 group by equ.data_location_id) temp1 where temp1.counts_total<10 group by temp1.typeid"
    //Slie 37:Average percentage of equipments per facility having a preventive maintenance plan
    public static final String AVG_PERCENT_PREV_SIMPLE_SLD37="select count(provOrderTemp1.equipments)/(select  count(equ1.code) as total_equipents from memms_equipment equ1 where equ1.data_location_id @DATA_LOCATION) as final_result from (SELECT privOrder.equipment_id as equipments FROM memms_equipment equ,memms_preventive_order_abstract privOrder  where equ.id=privOrder.equipment_id and  equ.data_location_id @DATA_LOCATION group by privOrder.equipment_id) provOrderTemp1"
    public static final String AVG_PERCENT_PREV_GROUP_SLD37="select provOrderTemp1.typeName,count(provOrderTemp1.equipments)/(select  count(equ1.code) as total_equipents from memms_equipment equ1 where equ1.data_location_id @DATA_LOCATION) as final_result from (SELECT privOrder.equipment_id as equipments,locty.id as typeId,locty.names_en as typeName FROM memms_equipment equ,chai_location_data_location loc,chai_location_data_location_type locty,memms_preventive_order_abstract privOrder  where equ.data_location_id=loc.id and loc.type=locty.id and equ.id=privOrder.equipment_id and  equ.data_location_id @DATA_LOCATION group by privOrder.equipment_id) provOrderTemp1 group by provOrderTemp1.typeId"
    //Slie 38:Share of facilities with no preventive maintenance plan for more than 10%  of the equipment 
    public static final String SHARE_FAC_NO_PRIV_SIMPLE_SLD38="select count(tempp.nopreventions)/(select count(loc.id) as totalfac from chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.id)/(select  count(equ1.code) from memms_equipment equ1 where equ1.data_location_id @DATA_LOCATION ) as nopreventions FROM memms_equipment equ where equ.id not in(SELECT m.equipment_id FROM memms_preventive_order_abstract m) and equ.data_location_id @DATA_LOCATION  group by equ.data_location_id) tempp where tempp.nopreventions*100<=10"
    public static final String SHARE_FAC_NO_PRIV_GROUP_SLD38="select tempp.typeName,count(tempp.nopreventions)/(select count(loc.id) as totalfac from chai_location_data_location loc where loc.id @DATA_LOCATION) as final_result from (SELECT count(equ.id)/(select  count(equ1.code) from memms_equipment equ1 where equ1.data_location_id @DATA_LOCATION ) as nopreventions,locTy.id as typeid,locTy.names_en as typeName FROM memms_equipment equ,chai_location_data_location locc,chai_location_data_location_type locTy where equ.data_location_id=locc.id and locc.type=locTy.id and equ.id not in(SELECT m.equipment_id FROM memms_preventive_order_abstract m) and equ.data_location_id @DATA_LOCATION  group by equ.data_location_id) tempp where tempp.nopreventions*100<=10  group by tempp.typeid"
    //Slie 39:Share of warehouses with less than 20 spare part inventory status  changes in a month
    public static final String SHARE_WHERE_LESS_20_SIMPLE_SLD39="select count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc  where loc.id @DATA_LOCATION) as final_result from (SELECT count(spst.spare_part_id) as counts_total FROM memms_spare_part sp,memms_spare_part_status spst  where sp.id=spst.spare_part_id and sp.data_location_id @DATA_LOCATION and dateDiff(NOW(),spst.date_of_event) <=30 group by sp.data_location_id) temp1 where temp1.counts_total<=20;"
    public static final String SHARE_WHERE_LESS_20_GROUP_SLD39="select temp1.typeName,count(temp1.counts_total)/(select count(loc.id) as total_fac FROM chai_location_data_location loc  where loc.id @DATA_LOCATION) as final_result from (SELECT count(spst.spare_part_id) as counts_total,loctTy.id as typeid,loctTy.names_en as typeName FROM memms_spare_part sp,chai_location_data_location loct,chai_location_data_location_type loctTy,memms_spare_part_status spst  where sp.data_location_id=loct.id and loct.type=loctTy.id  and sp.id=spst.spare_part_id and sp.data_location_id @DATA_LOCATION and dateDiff(NOW(),spst.date_of_event) <=30 group by sp.data_location_id) temp1 where temp1.counts_total<=20 group by temp1.typeid;"
    
    
}

